[project]
name = "experiences-with-the-nationwide-collection-of-cancer-registry-data"
requires-python = ">= 3.11"
version = "0.9.0"
description = "Analysis and reporting on experiences with the nationwide collection of cancer registry data in Germany"
readme = "README.md"
dependencies = [
    "pip",
    "pandas",
    "numpy",
    "duckdb>=1.5.0",
    "pandas-plots>=2.1.0",
    "ipykernel",
    "jupyter-client",
    "jupyter",
]
